### ISSUE TITLE
Target Temperature

### ISSUE THREAD

**Issue by soler2000** [hellhond/be.geekness.tado#4]
When using target temperature has changed, the drop tag [measure_temperature] does not pass the value only the variable name.

**Comment by hellhond** [comment]
Can you check the current version (0.5.2) ?
This should work.

I've added "The target temperature has changed" trigger, which has a "temp" drop tag, and used the "Say something" action, with the "temp" drop tag as an input.

When I change the temperature in Homey, Homey says "20.5".
