### ISSUE TITLE
Driver not loading properly/Can't add device

### ISSUE THREAD

**Issue by swttt** [hellhond/be.geekness.tado#7]
Can't seem to add my thermostat.
When i try to add a device, i can't click the thermostat icon (spinning loading animation).

No errors in the console. Installed the app twice and did a few power cycles :/

**Comment by hellhond** [comment]
Just submitted a new version (0.5.5) of the app, waiting on Athom to approve.

There was a lingering issue which prevented the device driver to initialize for new installations, should be fixed with version 0.5.5.

**Comment by swttt** [comment]
Woot, thats amazing!
Thanks for the fast reply.
